#print("hello world!")
#print("hello again")
#print("i like typing this.")
#print("this is fun")
#print("yay! pringting.")
#print("i 'd much rather you 'not'.")
#print('i "sail"do not tonch this.')
print("hello world!")
print("hello again")
print("i like typing this.")
print("this is fun")
print("yay! pringting.")
print("i 'd much rather you 'not'.")
print('i "sail"do not tonch this.')

